package com.asraf.entities;
// Generated Aug 29, 2018 6:56:08 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OauthApprovals generated by hbm2java
 */
@Entity
@Table(name = "oauth_approvals", catalog = "myauthdb")
public class OauthApprovals extends BaseEntity implements java.io.Serializable {

	private OauthApprovalsId id;

	public OauthApprovals() {
	}

	public OauthApprovals(OauthApprovalsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userId")),
			@AttributeOverride(name = "clientId", column = @Column(name = "clientId")),
			@AttributeOverride(name = "scope", column = @Column(name = "scope")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 10)),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expiresAt", length = 19)),
			@AttributeOverride(name = "lastModifiedAt", column = @Column(name = "lastModifiedAt", length = 19)) })
	public OauthApprovalsId getId() {
		return this.id;
	}

	public void setId(OauthApprovalsId id) {
		this.id = id;
	}

}
